image: atlassian/default-image:2

pipelines:
  branches:
    feature/test-deploy:
      - step:
          size: 2x
          name: Build and deploy to the staging
          deployment: Staging
          script:
            - export NODE_OPTIONS=--max-old-space-size=6144
            - npm i
            - npm run build
            - ssh -p $ARTKAI_DEV_PORT $ARTKAI_DEV_USER@$ARTKAI_DEV_HOST 'rm -rf quipy-portal/*'
            - tar -cf build.tar.gz build
            - scp -P $ARTKAI_DEV_PORT -r build.tar.gz $ARTKAI_DEV_USER@$ARTKAI_DEV_HOST:quipy-portal/
            - ssh -p $ARTKAI_DEV_PORT $ARTKAI_DEV_USER@$ARTKAI_DEV_HOST 'cd quipy-portal/ && tar -xvf build.tar.gz && mv ./build/* ./ && rm -rf ./build.tar.gz && rm -rf ./build'
